name: Server sent event CI/CD 

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: github.actor == 'cuongnms'

    steps:
      - name: Check whoami
        run: whoami

      - name: Debug sudo
        run: sudo -n -l

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build binary
        run: |
          go build -o server-sent-event .

      - name: Deploy app
        run: |
          sudo -n /usr/bin/systemctl stop server-sent-event || true
          sudo -n cp ./server-sent-event /opt/go/server-sent-event
          sudo -n /usr/bin/systemctl start server-sent-event
